# Generated by Django 3.0 on 2020-01-27 12:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('believe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='password',
            field=models.TextField(default=111111, verbose_name='密码'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userdata',
            name='birthday',
            field=models.DateTimeField(default=datetime.datetime(2000, 1, 1, 0, 0), verbose_name='生日'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='telephone',
            field=models.TextField(unique=True, verbose_name='电话'),
        ),
    ]
