# Generated by Django 3.0 on 2020-02-18 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('believe', '0003_frinendmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frinendmodel',
            name='friendTel',
            field=models.TextField(verbose_name='好友电话'),
        ),
        migrations.AlterField(
            model_name='frinendmodel',
            name='telephone',
            field=models.TextField(verbose_name='电话'),
        ),
    ]
