# Generated by Django 3.0 on 2020-03-02 12:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('believe', '0004_auto_20200218_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='frinendmodel',
            name='loginIP',
            field=models.TextField(default='0.0.0.0', verbose_name='登陆IP'),
        ),
        migrations.AddField(
            model_name='userdata',
            name='loginIP',
            field=models.TextField(default='0.0.0.0', verbose_name='登陆IP'),
        ),
        migrations.AddField(
            model_name='userdata',
            name='loginTime',
            field=models.DateTimeField(default=datetime.datetime(2000, 1, 1, 0, 0), verbose_name='登陆时间'),
        ),
    ]
